### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#1534]
<img width="587" alt="Screen Shot 2022-02-28 at 4 53 11 PM" src="https://user-images.githubusercontent.com/686933/156084005-8dc5008a-a8cc-4823-a305-8e050c5d63a4.png">

**Comment by evo777** [comment]
Dark mode for C0d3 is good.

**Comment by shockz09** [comment]
dark mode will be a good feature to implement , if i will get time from exams , i will try for sure :shipit:

**Comment by flacial** [comment]
shipit invaded GitHub @mino323 😂

**Comment by flacial** [comment]
What do you think about migrating from Bootstrap to https://tailwindcss.com/?

**Comment by shockz09** [comment]
@flacial 

tailwind css will be much better in my opinion

**Comment by evo777** [comment]
Tailwind CSS is good.

**Comment by songz** [comment]
I added darkmode support to my [note taking site](https://notes.songz.dev/), this is what I did: https://github.com/songz/noteapp/pull/30/files

**Comment by SlyBouhafs** [comment]
I think there's an easy way to achieve dark mode, if we have css color variables for light and dark mode, depending on what the client prefers, we can switch between light mode and dark mode using a toggle button by changing the `data-theme` attribute. Something like this:
```css
html[data-theme="dark"] {
  --color-bg: #000000;
}

html[data-theme="light"] {
  --color-bg: #ffffff;
}

.element {
  background-color: var(--color-bg);
}
```

**Comment by SlyBouhafs** [comment]
I think there's an easy way to achieve dark mode, if we have css color variables for light and dark mode, depending on what the client prefers, we can switch between light mode and dark mode using a toggle button by changing the `data-theme` attribute. Something like this:
```css
html[data-theme="dark"] {
  --color-bg: #000000;
}

html[data-theme="light"] {
  --color-bg: #ffffff;
}

.element {
  background-color: var(--color-bg);
}
```
This way, all we have to is write new color variables and update our elements to use those colors to make the toggle switch work.
